version: '3.1'

services:
  main:
      container_name: gini
      build: .
      volumes:
          - .:/opt/gini
      working_dir: /opt/gini
      ports:
          - 8082:8080
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: gini
      POSTGRES_PASSWORD: gini
      POSTGRES_DB: gini

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8085:8080
